### ISSUE TITLE
Homestead

### ISSUE THREAD

**Issue by jpkontreras** [jadjoubran/laravel5-angular-material-starter#370]
- **I'm submitting a ...**
- [ ] undocumented feature i guess 

The thing is that i managed to install this on a laravel homestead vagrant box
all running great  gulp && gulp watch . 
But when i want to show it with php artisan serve i get errors on the browser
I  did it without php artisan serve did not work neither 

How can i serve the project from laravel/homestead .. Maybe PM2 idk really

Thank you 
- **Laravel & Angular version:** 3.2.0

**Comment by flick36** [comment]
umm Vagrant it's a virtual machine if you run `php artisan serve` you are running it in the virtual machine so you'll have to open a browser in that machine wich it's almost imposibble since it's just a Command-line interface SO you gonna need to map the Ip address of the virtual machin to your hosts file read a tutorial here's one https://scotch.io/tutorials/getting-started-with-laravel-homestead

It's not a undocumented feature since homestead and vagrant weren't created here xD

Also there have been some issues with Vagrant + Windows as you can read here in the [docs](https://laravel-angular.readme.io/docs/install)

These [issues](https://github.com/jadjoubran/laravel5-angular-material-starter/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Aenvironment%3Avagrant+) might help

**Comment by ptondereau** [comment]
Hello @jpkontreras 

Can you please copy/paste your errors here please ?

**Comment by jpkontreras** [comment]
@ptondereau  The error im getting is a 403 Forbidden and with :8000 im getting ERR_CONNECTION_REFUSED

@flick36  I did read the docs from this starter and the laravel docs . Also i did map the site in my homestead.yaml . I  did it without serve and it was not working neither do. 
Do you think that i should map nginx.conf to make this work . I append here the homestead yaml and my hosts  file. 

OS: Windows 10 X64

```
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: C:\Users\patri\Code
      to: /home/vagrant/Code

sites:
    - map: phpmyadmin.app
      to: /home/vagrant/phpmyadmin

    - map: angular.app
      to: /home/vagrant/Code/projecto/

    - map: homestead.app
      to: /home/vagrant/Code/asg/


databases:
    - homestead


-------Hosts file --------


# localhost name resolution is handled within DNS itself.
#   127.0.0.1       localhost
#   ::1             localhost
127.0.0.1 phpmyadmin.app
#192.168.10.10  homestead.app
192.168.10.10  angular.app


```
